# Feature Extraction

## Import Packages and Dataset

In [1]:
import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

import nltk
from sklearn.feature_extraction.text import TfidfVectorizer

import warnings
warnings.filterwarnings("ignore")

In [2]:
data_train = pd.read_csv("Data/data_train.csv",sep=";")
data_test = pd.read_csv("Data/data_test.csv",sep=";")

In [3]:
data_train.head()

,Tweet,Tweet_Parsed,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,Lengserkan kenapa om.. dpr kan punya kuasa rak...,lengser om dewan wakil rakyat kuasa rakyat ber...,1,0,1,0,0,0,0,0,1,0,0,1
1,Presiden Joko Widodo (Jokowi) meminta agar Sis...,presiden joko widodo jokowi sistem izin usaha ...,0,0,0,0,0,0,0,0,0,0,0,0
2,luggage semua harga yahudi \xf0\x9f\x98\xb9',luggage harga yahudi,0,0,0,0,0,0,0,0,0,0,0,0
3,Pegimana ini? ð?¤­ RT USER: Menarik!; ; Meskip...,tarik kaos tulis ganti gubernur jawa semangat ...,0,0,0,0,0,0,0,0,0,0,0,0
4,makanya drpd pusing cari yg sdh hilang..mendin...,pusing cari hilang mending urus surat dkp tent...,1,0,1,0,0,0,0,0,1,1,0,0

In [4]:
data_test.head()

,Tweet,Tweet_Parsed,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,USER USER Ewe ewe berhadiah',ngewe ngewe hadiah,0,1,0,0,0,0,0,0,0,0,0,0
1,"Pada tahun 2045, Indonesia diprediksikan mjd n...",indonesia prediksi negara ekonomi no dunia era...,0,0,0,0,0,0,0,0,0,0,0,0
2,"Ini baru ""BERITA""; ; PPP TOLAK PENCAPRESAN JOK...",berita ppp tolak calon presiden jokowi dukung ...,0,0,0,0,0,0,0,0,0,0,0,0
3,"USER, Resident Country Director USER: Pertumbu...",residen country director tumbuh ekonomi lestar...,0,0,0,0,0,0,0,0,0,0,0,0
4,UMAT HINDU SAMPAIKAN SELAMAT ULANG TAHUN KEPAD...,umat hindu selamat ulang presiden soeharto,0,0,0,0,0,0,0,0,0,0,0,0

## TF-IDF

In [5]:
X_train = data_train['Tweet_Parsed']
X_test = data_test['Tweet_Parsed']
y_train = data_train.drop(['Tweet','Tweet_Parsed'],axis=1)
y_test = data_test.drop(['Tweet','Tweet_Parsed'],axis=1)

In [6]:
# Parameter election
ngram_range = (1,1)
min_df = 1
max_df = 1.
max_features = 300

In [7]:
tfidf = TfidfVectorizer(encoding='utf-8',
                        ngram_range=ngram_range,
                        stop_words=None,
                        lowercase=False,
                        max_df=max_df,
                        min_df=min_df,
                        max_features=max_features,
                        norm='l2')
#                         sublinear_tf=True)

In [8]:
features_train = tfidf.fit_transform(X_train).toarray()
labels_train = y_train
print(features_train.shape)

(11193, 300)

In [9]:
features_test = tfidf.transform(X_test).toarray()
labels_test = y_test
print(features_test.shape)

(1976, 300)

In [10]:
fitur = tfidf.get_feature_names()
target = data_train.drop(['Tweet','Tweet_Parsed'],axis = 1).columns

In [11]:
data_train_tfidf = pd.DataFrame(data=features_train,columns=fitur)
data_train_tfidf = data_train_tfidf.join(pd.DataFrame(data=y_train,columns=target))
data_train_tfidf.head()

,adil,aduh,agama,ah,ahok,ajak,ajar,akun,al,allah,...,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,1,0,0,1
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.499709,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,1,1,0,0

In [12]:
data_test_tfidf = pd.DataFrame(data=features_test,columns=fitur)
data_test_tfidf = data_test_tfidf.join(pd.DataFrame(data=y_test,columns=target))
data_test_tfidf.head()

,adil,aduh,agama,ah,ahok,ajak,ajar,akun,al,allah,...,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

## Save File

In [13]:
data_train_tfidf.to_csv('Data/data_train_tfidf.csv', index = False)
data_test_tfidf.to_csv('Data/data_test_tfidf.csv', index = False)